---
- name: OpenFaaS deployment on Cherry Servers
  connection: local
  gather_facts: true
  remote_user: root
  hosts: localhost
  tasks:
  - name: Deploying master node
    cherryservers_server:
      hostname:
        - "{{ master_hostname }}"
      plan_id: "{{ plan_id }}"
      project_id: "{{ project_id }}"
      image: "{{ image }}"
      region: "{{ region }}"
      state: active
      count: "{{ number_of_masters }}"
      count_offset: 1
      ssh_label:
        - openfaas_ansible
    register: master

  - name: Register master node
    add_host:
      hostname: "{{ master.server[0].ip_addresses[0].address }}"
      group: "master_server"
   
  - set_fact: master_server_ip="{{ master.server[0].ip_addresses[0].address }}"

- name: Preparing the master node and registering necessary variables
  connection: ssh
  remote_user: root
  hosts: master_server
  tasks:
  - shell: "while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done;"      
  - apt:
      update_cache: yes
  - apt:
      name: "{{ packages }}"   
    vars:
      packages:
        - git
        - curl
        - jq
  - get_url:
      url: https://download.docker.com/linux/ubuntu/dists/zesty/pool/stable/amd64/docker-ce_17.12.0~ce-0~ubuntu_amd64.deb
      dest: /tmp/docker-ce_17.12.0~ce-0~ubuntu_amd64.deb
  - apt:
      deb: /tmp/docker-ce_17.12.0~ce-0~ubuntu_amd64.deb
      state: present
  - git:
      repo: https://github.com/openfaas/faas.git
      dest: /faas
  - get_url:
      url: https://cli.openfaas.com
      dest: /faas-cli.sh
      mode: o=x
  - command: "sh /faas-cli.sh"
  - command: "docker swarm init --advertise-addr {{ hostvars.localhost.groups.master_server[0] }}"
  - command: "docker swarm join-token -q worker"
    register: worker_token
  - add_host:
      name: "worker_token"
      token: "{{ worker_token.stdout }}"
       
- name: Deploying the worker nodes
  connection: ssh
  gather_facts: true
  hosts: localhost
  remote_user: root
  tasks:
  - name: Deploying worker server(s)
    cherryservers_server:
      hostname:
        - "{{ worker_hostname }}"
      plan_id: "{{ plan_id }}"
      project_id: "{{ project_id }}"
      image: "{{ image }}"
      region: "{{ region }}"
      state: active
      count: "{{ number_of_workers }}"
      count_offset: 1
      ssh_label:
        - openfaas_ansible
    register: worker

  - name: Register first worker node
    add_host:
      hostname: "{{ worker.server[0].ip_addresses[0].address }}"
      group: "worker_server"
  - name: Register other worker nodes
    add_host:
      hostname: "{{ worker.server[item|int].ip_addresses[0].address }}"
      group: "worker_server"
    with_sequence: "start=1 end={{ number_of_workers -1 }}"
    
- name: Preparing the worker node(s)
  connection: ssh
  remote_user: root
  hosts: worker_server
  tasks:
  - shell: "while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done;"
  - apt:
      update_cache: yes
  - apt:
      name: "{{ packages }}"   
    vars:
      packages:
        - git
        - curl
        - jq
  - get_url:
      url: https://download.docker.com/linux/ubuntu/dists/zesty/pool/stable/amd64/docker-ce_17.12.0~ce-0~ubuntu_amd64.deb
      dest: /tmp/docker-ce_17.12.0~ce-0~ubuntu_amd64.deb
  - apt:
      deb: /tmp/docker-ce_17.12.0~ce-0~ubuntu_amd64.deb
      state: present
  - command: "docker swarm join --token {{ hostvars['worker_token']['token'] }} {{ hostvars.localhost.groups.master_server[0] }}:2377"
  - debug:
      msg: "Playbook complete. Master server IP is {{ hostvars.localhost.groups.master_server[0] }}"
    run_once: true
