---
- name: Cherry Servers API module
  connection: local
  hosts: localhost
  tasks:
  - name: Terminating master node(s)
    cherryservers_server:
      project_id: '{{ project_id }}'
      hostname:
        -  "{{ master_hostname }}"
      count: "{{ number_of_masters }}"
      count_offset: 1    
      state: absent
  - name: Terminating worker node(s)
    cherryservers_server:
      project_id: '{{ project_id }}'
      hostname:
        -  "{{ worker_hostname }}"
      count: "{{ number_of_workers}}"
      count_offset: 1    
      state: absent
